# Generated by Django 4.1 on 2024-02-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                ("reg_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("tel", models.CharField(max_length=20)),
                ("des", models.TextField()),
                ("pay", models.CharField(max_length=20)),
                ("current_time", models.DateTimeField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("remain_day", models.IntegerField()),
            ],
        ),
    ]
