# Generated by Django 4.1 on 2024-02-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="current_time",
            field=models.CharField(max_length=20),
        ),
    ]
