# Generated by Django 4.1 on 2024-02-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0002_alter_register_current_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("des", models.TextField()),
                ("pay", models.CharField(max_length=20)),
                ("current_time", models.CharField(max_length=20)),
                ("date", models.DateField()),
            ],
        ),
    ]
