# Generated by Django 4.1 on 2024-02-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0003_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member_checkin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("tel", models.CharField(max_length=15)),
                ("des", models.TextField()),
                ("reg_current_time", models.CharField(max_length=20)),
                ("date", models.DateField()),
            ],
        ),
    ]
