# Generated by Django 4.1 on 2024-03-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0004_member_checkin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member_checkin",
            name="id",
        ),
        migrations.AddField(
            model_name="member_checkin",
            name="mem_check_id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
